apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mirror-route
  namespace: traefik
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
  hostnames:
  - mirror.example
  rules:
  - backendRefs:
    - name: my-app-primary
      port: 80
      namespace: default
    filters:
    - type: RequestMirror      # This was correct
      requestMirror:           # This structure was wrong
        backendRef:            # Changed to match the spec
          group: ""           # Added
          kind: Service       # Added
          name: my-app-mirror
          namespace: default
          port: 80