apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik.yaml: |
    experimental:
      kubernetesGateway: true
    providers:
      kubernetesGateway:
        enabled: true
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
    api:
      dashboard: true
      insecure: true