providers:
  kubernetesCRD:
    enabled: true
  kubernetesGateway:
    enabled: true
  kubernetesIngress:
    enabled: false

gateway:
  namespacePolicy: All

ingressRoute:
  dashboard:
    enabled: true