# https://taskfile.dev

version: '3'


includes:
  nix: taskfiles/nix.taskfile.yml
  devenv: taskfiles/devenv.taskfile.yml
  direnv: taskfiles/direnv.taskfile.yml  

  cookiecutter: taskfiles/cookiecutter.taskfile.yml
  steampipe: taskfiles/steampipe.taskfile.yml
  duckdb: taskfiles/duckdb.taskfile.yml

  vhs: taskfiles/vhs.taskfile.yml 
  asciinema: taskfiles/asciinema.taskfile.yml
  
  silicon: taskfiles/silicon.taskfile.yml

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
