# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

includes:
  go: tools/taskfiles/go.taskfile.yml
  docker: tools/taskfiles/docker.taskfile.yml
  k3d: tools/taskfiles/k8s.k3d.taskfile.yml
  app: tools/taskfiles/app.taskfile.yml  

tasks:
  default:
    cmds:
      - task: app
