# https://taskfile.dev

version: '3'

tasks: 
  dashboard:
    cmds:
      - task: dashboard:open
      - task: dashboard:pf

  dashboard:pf:
    cmds:
      - kubectl -n kube-system port-forward {{.TRAEFIK_POD_NAME}} 9000:9000
    vars:
      TRAEFIK_POD_NAME:
        sh: kubectl get pods -n kube-system --selector "app.kubernetes.io/name=traefik" --output=name

  dashboard:open:
    cmds:
      - open http://localhost:9000/dashboard/