# https://taskfile.dev

version: '3'


includes:
  base: taskfiles/base.taskfile.yaml
  xsv: taskfiles/xsv.taskfile.yaml
  sqlpkg: taskfiles/sqlpkg.taskfile.yaml
  sqlean: taskfiles/sqlean.taskfile.yaml


