[project]
name = "llamaindex-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llama-index-embeddings-huggingface>=0.4.0",
    "llama-index-llms-ollama>=0.4.2",
    "llama-index>=0.12.3",
]
