# https://taskfile.dev

version: '3'


includes:
  silicon: taskfiles/silicon.taskfile.yml

  k8s-k3d: taskfiles/k8s.k3d.taskfile.yml
  traefik: taskfiles/traefik.taskfile.yml

  my-app: taskfiles/my-app.taskfile.yml
  
tasks:
  default:
    cmds:
      - task --list-all
    silent: true
