apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tilt-go-sample-app
  name: tilt-go-sample-app
spec:
  containers:
  - image: ttl.sh/tilt-go-sample-app:latest
    name: tilt-go-sample-app
    envFrom:
    - configMapRef:
        name: app
    ports:
    - containerPort: 8085
  dnsPolicy: ClusterFirst
  restartPolicy: Always
